DDD-5/ios-tooda

Tooda/Sources/Common/UIColor+Extension.swift
- class var를 사용해서 hex 값으로 가져오는 extnension을 추가하였습니다. 
- 기존에 사용하던 AppColor는 optional binding이 불가피해서 class var를 사용하는 코드를 추가하였어요.
- AppColor에는 deprecated를 달아 추후에 제거 예정입니다.
=> UIColor Extension 추가

Tooda/Sources/Core/AppInject.swift, Tooda/Sources/Utils/KeyChainService.swift, Tooda/Sources/Utils/LocalPersistanceManager.swift, Tooda/Sources/Utils/UserDefaultsService.swift
- LocalPersistanceManager 추가
- 향후 Realm이 추가될 수도 있을 것 같아서 generic하게 쓸 수 있도록 protocol(LocalPersistenceServiceType)을 수정하고
LocalPersistanceManager를 통해 값을 set, fetch 할 수 있도록 통합했습니다
- Usage
```swift
// set
LocalPersistanceManager.keychain.set(value: token, forKey: .appToken)
LocalPersistanceManager.userDefaults.set(value: isFirstUser, forKey: .firstUser)
// fetch
LocalPersistanceManager.keychain.value(forKey: .appToken)
LocalPersistanceManager.userDefaults.value(forKey: .firstUser)
```
=> [Core] 로그인 토큰 저장을 위한 KeyChainService 및 LocalPersistanceManager 추가

Tooda/Sources/Entities/Note/Note.swift, Tooda/Sources/Entities/Note/NoteLink.swift, Tooda/Sources/Entities/Note/NoteStock.swift
- 노트 등록, 조회를 위한 Entities를 서버 스펙에 맞게 변경하였습니다.
- Note, NoteLink의 codingKey를 서버 요구사항에 맞게 변경했어요.
- StockChangeState의 case 명을 대문자로 변경했어요.
=> [Entity] 노트 관련 Entities 변경

Tooda/Sources/Common/AuthorizationService.swift, Tooda/Sources/Common/RxAuthorization.swift, Tooda/Sources/Core/AppInject.swift, Tooda/Sources/SupportFiles/Info.plist
- 앱내에서 사용할 권한을 관리하는 Service를 추가하였습니다.
- AuthorizationService는 푸시알림, 사진권한의 상태를 Observable로 구독할 수 있습니다.
- 사진 권한을 요청할 때 필요한 문구를 info.plist에 추가하였습니다.
사용방법
```
let service = self.dependency.authorizationService
return service.photoLibrary.flatMap { [weak self] status -> Observable<Mutation> in
switch status {
case .authorized:
guard let mutation = self?.didSelectedItem(indexPath) else { return .empty() }
return mutation
default:
return .just(Mutation.requestPermissionMessage("테스트"))
}
}
```
=> [Util] AuthorizationService 추가

Tooda/Sources/Base/BaseViewController.swift, Tooda/Sources/Common/Extensions/Date+Extension.swift
- 이슈 확인을 위해 함수 call print
| Before | After |
|----|----|
| <img width="619" alt="스크린샷 2021-07-31 오후 6 38 28" src="https://user-images.githubusercontent.com/31857308/127736011-28533bec-4601-4766-88fe-1fe1bbd8ee21.png"> | <img width="617" alt="스크린샷 2021-07-31 오후 6 35 14" src="https://user-images.githubusercontent.com/31857308/127736016-d66e2456-93a0-4114-ac50-53ae4532853d.png"> |
- 기존에는 reactor bind가 viewDidLoad 이후 불려서 rx.viewDidLoad를 사용할 수 없었음
- 명확한 원인을 파악한 것은 아니지만 init에서 다른 작업이 이뤄지면서 aync로 viewDidLoad가 먼저 불리는게 아닐까 가설을 세우고
init에서 다른 함수 call을 viewDidLoad로 이동
```swift
override func viewDidLoad() {
super.viewDidLoad()
configureUI()
configureConstraints()
}
```
=> ViewDidLoad, Reactor Bind 함수 call 순서 이슈 수정

Tooda/Sources/Scenes/Home/Cells/NotebookCell.swift, Tooda/Sources/Scenes/Home/HomeViewController.swift
- Typo -> Font Renaming
- 명확한 의미 전달을 위해 타이핑 실수라는 뜻의 Typo대신 Font 네임 사용으로 수정
=> [Core] Rename Typo to Font

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Entities/Note/NoteImage.swift, Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteImageItemCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteLinkCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteImageItemCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteStockCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteImageItemCellReactor.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageItemCellReactor.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/CreateNote/Section/NoteImageSection.swift
- 노트 등록 화면에서 이미지 셀을 추가하기 위한 UI작업을 진행했어요.
- NoteImageSection을 추가했어요, ImageCell의 셀의 역할을 분리하기 위해 섹션을 나눴어요.
- EmptyNoteImageCell을 추가했어요. 탭하면 사진과 관련된 권한을 물어보고, 이미지 피커를 보여주는 역할을 담당할거에요.
- NoteItemImageCell을 추가했어요. 이미지 상단의 x 버튼을 눌렀을 때, 아이템을 삭제하는 기능을 추가할 예정이에요.
- Note Section Factory에 이미지 셀과 관련된 코드를 추가했어요. 이미지 셀 이벤트를 처리하기위해 AuthorizationType과 coordinator를 주입받게 기능을 추가했어요.
=> [UI] 노트 등록 화면에서 이미지 셀을 추가했어요.

Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- imageCellReactor에 Dependency와 기타 비즈니스 로직을 변경했어요.
- cellReactor에서 많은 로직들을 가져가기 보다는 ViewControllerReacto에서 가져가는게 좋겠다고 생각이 들었어요. 그래서 imageCellReactor의 비즈니스 로직을 노트작성 Reactor로 변경하는 작업을 진행하려고해요. 
- ImageCellReactor에서 RxAuthorization과 coordinator에 대한 의존성을 제거했어요. 제거한 로직은 다음 PR에 노트작성 Reactor로 반영할 예정입니다!
- ImageCell의 Selected Item을 전달하기위해 Reactive Extension을 추가했어요.
=> [Domain] 노트 imageCellReactor를 리팩토링했어요.

Tooda/Sources/Common/Extensions/UIViewController+Extension.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- 노트 이미지 셀에서 하위 컬렉션 아이템을 선택할 때 선택한 아이템에 따라 다른 기능을 추가했어요.
- 노트 이미지 didSelectedItemCell Reactive Extension 기능을 dataSource에 바인딩했어요.
- CreateNoteViewController에 didSelectedImageItem 기능을 추가했어요.
- didSelectedImageItem의 기능을 러프하게 구현했어요.
- 이미지를 탭했을 때, 사진 관련 권한을 체크하고, 권한이 체크되어 있지 않으면 퍼미션 관련 Alert을 보내요.
- 첫번째 이미지셀의 아이템을 탭했을 때, 아이템의 갯수가 최대 3개 미만까지는 이미지 등록 관련 기능을 수행할 예정이에요.
=> [UI] 노트 등록 이미지 탭 관련 기능을 추가했어요.

Tooda/Sources/Common/UIColor+Extension.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/Home/Cells/NotebookCell.swift, Tooda/Sources/Scenes/Home/HomeViewController.swift
- 노트 등록화면에 ImagePicker 관련 코드 추가,  Delegate 코드 구현, Reactor Action, Mutation 정의
- 노트 등록 ViewController에서 showPhotoPicker 메소드를 추가했어요.
- 노트 등록 ViewController에서 imagePickerController Delegate 코드를 구현했어요.
- ImagePickerController Delegate에서 전달받은 ImageData는 Reactor Action으로 보내요.
- 노트 등록 Reactor에서 addImage 관련 request 메소드를 추가했어요.
- 노트 등록 Reactor에서 불필요한 SelectedItem Action case를 제거했어요.
=> [UI] 노트 등록 화면에 ImagePickerController를 연결했어요.

Tooda/Sources/Common/Extensions/UITableViewCell+Extension.swift
- indexPath 없이 reuseIdentifier 만으로 dequeue cell 하는 함수가 없어서 추가
```swift
func dequeue<T>(_ cellType: T.Type) -> T where T: CellType {
return self.dequeueReusableCell(withIdentifier: T.reuseIdentifier) as! T
}
```
=> [UI/Util] UITableView dequeue cell extension 함수 추가했어요

Tooda/Sources/Scenes/AddStock/AddStockReactor.swift, Tooda/Sources/Scenes/AddStock/AddStockViewController.swift, Tooda/Sources/Scenes/AddStock/Cells/StockItemCell.swift, Tooda/Sources/Scenes/AddStock/Cells/StockItemCellReactor.swift, Tooda/Sources/Scenes/AddStock/Section/AddStockSection.swift
- AddStockViewController 에서 사용할 boilerplate code를 추가했어요. (Reactor, Section, Cell, CellReactor)
=> [UI] 종목 추가 화면의 보일러플레이트 코드를 추가했어요.

Tooda/Sources/Common/MarginLabel.swift
- margin 정해서 사용할 수 있는 MarginLabel 추가
- 여기에서 사용할 예정
=> [UI] 커스텀 MarginLabel 추가

Tooda/Sources/Base/BaseViewController.swift, Tooda/Sources/Common/Extensions/UIBarButtonItem+Extension.swift, Tooda/Sources/Scenes/Home/HomeViewController.swift, Tooda/Sources/Scenes/Search/SearchReactor.swift, Tooda/Sources/Scenes/Search/SearchViewController.swift
- 네비게이션바 백버튼을 커스터마이징 해서 close도 coordinator를 거치게 해요.
- 
- 다음과 같이 백버튼이 필요한 화면에는 viewDidload와 flatMap해서 configure하시면 될 것 같아요.
- Coordinator가 매우 문제가 많네요. 나중에 리팩토링 할 일 생기면 코디네이터 덜어내야될 것 같아요.
=> [Bug] 네비게이션바 백버튼을 하면 current 히스토리가 안 남는 문제를 수정합니다.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Networking/API/SotckAPI.swift, Tooda/Sources/Scenes/AddStock/AddStockReactor.swift, Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
- 종목 검색 화면에서 API 사용을 위해 NetworkingProtocol의 Dependency를 추가했어요.
- 종목 검색 텍스트 필드의 값이 입력되면 service 로직을 수행하고 response를 Observable String으로 전달받게끔 구현했어요.
- 닫기 버튼의 로직을 구현하기 위해 coordinator의 Dependency를 추가했어요.
- 닫기 버튼 입력 행위에 대한 Action을 바인딩하고 Mutation 로직을 구현했어요.
=> [UI] 종목 기록하기 화면의 입력 기능을 구현했어요.

Tooda/Sources/Common/Keyboard+LayoutGuide.swift, Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
- 키보드 영역에 컨텐츠를 붙이기 위해 써드파티 코드를 추가했어요. [참고](https://github.com/freshOS/KeyboardLayoutGuide)
- 종목 검색하기 화면에 다음 버튼을 추가하고 키보드 상단에 붙였어요.
=> [UI] 종목 검색하기 화면에서 다음 버튼을 추가하고 키보드 영역에 붙여요.

Tooda/Sources/Common/UIColor+Extension.swift, Tooda/Sources/Scenes/AddStock/AddStockReactor.swift, Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
- TableView Selected 이벤트를 전달하기 위해 Reactor Action을 정의하고 ViewController에 바인딩시켰어요.
- 테이블 셀 아이템이 선택되면 CurrentSection에 존재하는 Reactor에서 Dependency에 있는 name 값의 여부를 전달하기 위한 Mutation case를 정의했어요.
- 종목 검색하기 Reactor State에 ButtonEnabled의 프로퍼티를 정의하고 ViewController에서 State를 바인딩시켰어요.
- NextButton의 BackgroundColor를 변경하기 위한 메소드를 정의했어요.
=> [UI] 종목 기록하기 검색 결과 셀을 터치하면 다음버튼이 활성화 되어요.

Tooda/Sources/Scenes/AddStock/View/RateButton.swift, Tooda/Sources/Scenes/AddStock/View/RateSelectView.swift
- 종목 변동률 선택 버튼을 정의하고 UI 코드를 구현했어요.
- 변동률(상승, 유지, 하락)이 한꺼번에 들어있는 변동률 선택 뷰를 정의하고 UI를 구현했어요.
- 변동 타입 선택 뷰에 ViewController에서 선택된 버튼의 타입을 전달받기 위한 Reactive Extension 프로퍼티를 정의했어요.
=> [UI] 종목 변동률 선택 버튼과, 변동률 타입 선택 뷰를 추가했어요.

Tooda/Sources/Core/Coordinator/AppCoordinator.swift
- ViewController를 push 할 때, 현재 ViewController가 NavigationController에 감싸진 상태와 그렇지 않은 상태에서의 pushViewController 메소드를 추가하고 transition 메소드 내부에 코드를 추가했어요.
=> [Util] CurrentViewController의 NavigationController 여부에 따라 Push 로직을 변경했어요.

Tooda/Sources/Scenes/AddStock/StockRateInputReactor.swift, Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift, Tooda/Sources/Scenes/AddStock/View/RateSelectView.swift
- 뒤로가기 버튼 기능을 구현했어요.
- "추가하기 버튼" UI를 추가하고 기능을 구현했어요.
- 유지 버튼을 누르면 텍스트 필드 영역과 퍼센트 레이블을 숨김처리하고 추가하기 버튼을 활성화해요.
- 텍스트필드의 값이 입력되면 토글된 상태와 입력 값에 따라 추가하기 버튼이 활성화 되어요.
- 추가하기 버튼이 활성화 되어있을 때, 버튼을 누르면 이전 화면에 데이터를 전달하고 화면을 내려줘요.
|상승, 하강 상태|
|---------------------|
|![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/19662529/144733657-34f21fa6-4f80-425f-83ac-036855bf43fe.gif)|
|유지 상태|
|---------------------|
|![ezgif com-gif-maker](https://user-images.githubusercontent.com/19662529/144733692-708c09f2-51ce-4e5f-b5eb-0257c878fd19.gif)|
=> [UI] 변동률 입력 화면의 기능을 구현했어요.

Tooda/Sources/Entities/Note/NoteStock.swift, Tooda/Sources/Scenes/AddStock/StockRateInputReactor.swift, Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift, Tooda/Sources/Scenes/AddStock/View/RateSelectView.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteStockCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteStockCellReactor.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- 노트의 종목 셀 UI를 구현했어요.
- 노트 종목 셀 Reactor에 Payload 구조체를 정의하고 state에 멤버변수로 추가했어요.
- 종목 추가 하기 화면에서 추가 버튼을 누르면 입력된 정보를 바탕으로 노트 등록하기 화면에 새로운 SectionItem을 추가할 수 있게 Reactor에 localPublishRelay를 정의해주고, Transform 메소드를 통해 Action과 합성해주는 로직을 추가했어요.
- 노트 등록 화면에서 DataSource 클로저 블록에 노트 종목 셀과 관련된 case를 구현하고, tableView에 종목 셀을 등록시켰어요.
=> [Domain] 노트 등록화면에서 추가된 종목의 정보를 볼 수 있어요.

Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
- tableView delegate를 사용하기 위해 tableView 선언 타입을 변경했어요.
- 셀의 수정,삭제 UI를 표현하기 위해 DataSource에서 canEditRowAtIndexPath를 추가했어요.
- 셀 수정과 관련된 delegate 메소드를 구현했어요.
=> [UI] 노트 등록 화면에서 종목 아이템을 스와이프하면 수정, 삭제 UI를 볼 수 있어요.

Tooda/Sources/Common/Extensions/UIView+Extension.swift, Tooda/Sources/Scenes/CreateNote/View/CreateGuideView.swift, Tooda/Sources/Scenes/CreateNote/View/CreateNoteGuideView.swift
- 노트 등록 가이드 뷰를 커스텀 뷰로 만들었어요.
- 노트 등록 가이드 뷰의 탭 이벤트를 전달할 델리게이트를 선언했어요.
=> [UI] 홈화면에 표시될 노트 등록 안내 화면을 구현했어요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Scenes/Home/HomeReactor.swift, Tooda/Sources/Scenes/Home/HomeViewController.swift
- 홈화면에서 노트 등록 가이드 뷰를 정의하고 view에 추가하고 제약을 설정했어요.
- 노트 등록 가이드 뷰에 델리게이트를 연결하고, rxNoteGuideViewTap로 델리게이트 로직과 연결했어요.
- 홈 Reactor에서 노트 등록 화면을 호출하기 위한 Action과 Mutation에서 코디네이팅 로직을 구현했어요.
- AppFactory에서 CreateNoteViewController를 생성할 때 NavigationController를 감싸서 반환해줘요.
=> [Domain] 홈 화면에서 노트 등록 가이드 뷰가 보이고, 탭하면 노트 등록 화면을 볼 수 있어요.

Tooda/Sources/Common/Extensions/UIImage+Asset.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
- UIImage Extension에 link case 추가했어요.
- 노트 등록 화면에 링크 화면을 추가했어요.
- 노트 등록 화면에서 텍스트 필드가 아닌 뷰 영역을 탭하면 키보드가 내려갈 수 있게 제스처 메소드를 추가했어요.
=> [UI] 노트 등록 화면에 링크 화면을 추가했어요, 그 외 기타 기능 추가

Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
- NoteLinkCell의 UI 프로퍼티를 정의하고 제약조건을 정의했어요.
- 노트등록 화면의 DataSource 클로저에서 Link SectionItem Case를 구현했어요.
- 노트등록 화면에서 NoteLinkCell을 등록했어요.
=> [UI] 노트 링크 셀의 UI를 구현했어요.

Podfile, Tooda/Sources/Core/AppInject.swift, Tooda/Sources/Utils/LinkPreviewService.swift
- URL을 바탕으로 Rich링크를 생성해 줄 수 있는 써드파티 라이브러리를 PodFile에 추가했어요. [참고](https://github.com/LeonardoCardoso/SwiftLinkPreview)
- 리치 링크의 생성을 담당할 서비스에 대한 `LinkPreviewSerivceType`프로토콜을 정의하고 프로토콜을 채택한 `LinkPreviewSerivce` 클래스를 정의했어요.
- Dependency를 사용하는 쪽에서 SwiftLinkPreview에 대한 모듈 의존성을 모르게하기 위해 `LinkPreviewResponse` 구조체를 설계하고 escaping 전달인자로 사용해요.
- AppInject DI Container에서 LinkPreviewSerivceType을 등록했어요.
=> [Core] LinkPreview 라이브러리와 구현체를 추가했어요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteLinkCellReactor.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- 노트 등록 Reactor의 Dependency에 `LinkPreviewSerivce` 의존성을 추가했어요.
- 노트 등록 Reactor에서 Action에 전달받은 LinkURL로 LinkSectionItem을 그려주기 위한 Mutation, State 로직을 구현했어요.
-`NoteLinkCellReactor` 의 Dependency에 `LinkPreviewSerivce` 의존성을 추가했어요.
- `NoteLinkCellReactor`의 State에 linkResponse와 기타 UI를 변경하기 위한 State를 정의했어요.
- `NoteLinkCell`의 세부 UI를 구현하고 일부 프로퍼티의 이름을 컨텐츠에 맞게 변경했어요.
- NoteLinkCell에서 일부 StackView에 `translatesAutoresizingMaskIntoConstraints = false ` 속성이 미리 정해진건 Cell이 Configure 되는 시점에 UI가 깨지는 문제가 발생해서 이를 해결하기 위해 추가했어요.
- NoteLinkCell에 `LoadingIndicator` 를 추가했어요.
-  `NoteLinkCell` 의 Reactor Binding 코드를 추가했어요.
- `NoteImageCell`의 Size를 Figma 디자인대로 변경했어요.
=> [Domain] 노트 등록 화면에서 링크 아이템을 볼 수 있어요. 그 외 기타 변경건 1건

Tooda/Sources/SupportFiles/Info.plist
- Info.plist에서 App Build Number가 누락되어 앱을 실행할 수 없는 문제를 수정했어요.
=> [Util] Info.plist에서 App Build Number가 누락된 부분을 수정했어요.

Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/CreateNote/Section/NoteSection.swift
1. NoteSection Identity의 순서를 Figma에 보여지는 순서에 맞게 변경했어요.
2. `NoteContentCell` 의 private enum의 이름을 **Const**로 변경했어요. 그리고 화면에 사용할 상수 값을 정의했어요.
3. `NoteContentCell`의 제목 입력 필를 기본 UITextField로 변경하고 UI 코드를 Figma에 맞게 변경했어요.
4. `NoteContentCell`의 내용 필드를 UITextView로 변경하고 UI코드를 적용했어요.
5. `NoteContentCell`의 TextField와 UITextView Delegate를 연결하고, Extension 메소드를 구현했어요.
6. **종목기록하기**셀 의 layer border cornerRadius를 제거했어요.
6. **노트등록화면**의 타이틀을 커스텀 UILabel로 변경하고, 화면에 보여지는 DateString의 포맷을 변경했어요.
|**변경 전**|**변경 후**|
|------------|-----------|
|<img src="https://user-images.githubusercontent.com/19662529/148544607-3b9034dd-e369-4a39-b5a1-38b863383337.png" width=320>|<img src="https://user-images.githubusercontent.com/19662529/148544601-735b7f98-5c20-4ebc-ab56-02239d67decd.png" width=320>|
=> [Domain] 노트 등록 화면의 UI를 수정했어요.

Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
1. 등록 버튼을 추가하고 **노트등록화면**의 우측 상단 버튼에 연결했어요.
2. `NoteContentCell` 에서 textField와 textView의 입력을 전달받을 Reactive Extension property 구현했어요.
3. 노트 등록 Reactor에서 `NoteContentCell`의 타이틀과 내용 값이 변경되면 등록 버튼의 활성화 여부를 처리하기 위한 Action, Mutation을 정의하고 State에 프로퍼티를 추가했어요.
4. 노트 등록 화면에서 2번의 스트림을 `rxTextDidChangedRelay`에 바인딩하는 코드를 추가했어요. 또한 `rxTextDidChangedRelay` 에서 3번 Action으로 바인딩 하는 코드도 추가했어요.
=> [UI] 노트 등록 화면에 "등록" 버튼을 볼 수 있어요.

Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- `NoteContentCell` 의 Reactive Extension value에 comined prefix가 붙게 네이밍을 변경했어요.
- `CreateNoteViewController`에서 제목, 내용을 바인딩하는 PublishRelay의 네이밍을 변경했어요.
- `CreateNoteReactor`에서 제목, 내용을 전달받는 Action case의 이름을 변경했어요.
=> [Domain] 노트 등록 화면의 각종 이벤트의 네이밍을 변경했어요.

Tooda/Sources/Common/Extensions/Array+Extension.swift, Tooda/Sources/Entities/Note/AddNoteDTO.swift, Tooda/Sources/Entities/Note/NoteStock.swift
- Collection Type에서 사용할 수 있는 isNotEmpty Extension을 추가했어요
```
func aa() -> Bool {
return "aa".isNotEmpty
}
let result = ["a", "b", "c"].isNotEmpty
```
- StockChangeState를 사용하는 Entitiy를 파싱하는 과정에서 에러가 발생해 case에 rawValue를 별도로 지정해줬어요.
- AddNoteDTO의 프로퍼티중 프로퍼티 타입에서 옵셔널을 제거했어요.
=> [Entity/Utils] 노트 관련 Entities를 변경하고 유용한 Extension을 추가했어요.

Tooda/Sources/Entities/Note/AddNoteDTO.swift, Tooda/Sources/Entities/Note/NoteStock.swift, Tooda/Sources/Networking/API/NoteAPI.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- NoteStock을 parameter로 전달하기 위해 extension value를 추가했어요.
- AddNoteDTO에서 asParameter 메소드에서 sticker와 stocks를 전달 로직을 변경했어요.
- 노트 등록 Reactor에서 
- 노트 등록 화면에서 활성화 상태인 등록 버튼을 탭하면 한줄평 팝업을 호출해요. 한줄평 팝업의 이벤트를 전달받기 위해 Reactor에 별도 Relay를 추가하고 Action Transform에 추가했어요.
- 한줄평 팝업에서 스티커 선택이 끝나면 노트 등록 API를 호출해요. 노트 등록 API가 성공하고 Note Entity의 값에 따라 화면을 내려주도록 해요.
- 노트 입력 데이터를 저장하기 위해 Reactor에 addNoteDTO를 멤버변수로 정의하고, Action에서 전달되는 데이터를 Mutation Function 메소드에서 사이드 이펙트로 데이터를 변경시켜요.
=> [Domain] 노트 등록 화면에서 입력한 정보를 등록할 수 있어요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Core/Coordinator/Scene.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/View/CreateNoteGuideView.swift, Tooda/Sources/Scenes/Home/HomeReactor.swift, Tooda/Sources/Scenes/Home/HomeViewController.swift
- `Scene`의 CreateNote case에 DateString 파라미터를 추가했어요.
- Scene이 변경됨에 따라 `AppFactory`와 `HomeReactor`의 연결된 코드가 변경되었어요.
-`NoteGuideView`에 TodayString 프로퍼티를 추가했어요.
- `NoteGuideViewTapDelegate`에서 탭 메소드에 dateString 파라미터를 추가했어요.
- `HomeViewController`의 rxNoteGuideViewTap와 Delegate 메소드의 파라미터 타입을 변경했어요.
- `HomeReactor`에서 노트 등록화면을 호출할 때 DateString을 전달받기 위한 Reactor Action Command와 메소드에 파라미터를 정의했어요.
=> [Domain] 노트 가이드 뷰화면에 표시된 날짜 텍스트를 노트 등록화면에서 볼 수 있어요.

Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
- NoteListCell에서 shadow가 짤리는 이슈를 수정
- Before & After
<div>
</div>
=> [UI] NoteListCell에서 shadow가 짤리는 이슈를 수정했어요

Tooda/Sources/Core/SceneDelegate.swift, Tooda/Sources/Utils/KeyChainService.swift, Tooda/Sources/Utils/LocalPersistanceManager.swift, Tooda/Sources/Utils/UserDefaultsService.swift
- 첫 화면을 token 여부로 판단하도록 자동 로그인을 구현
- persistence value 제거를 위한 delete 함수를 추가
=> [Core] 자동 로그인을 구현했어요

Tooda/Sources/Entities/Note/Note.swift, Tooda/Sources/Entities/Note/NoteListDTO.swift, Tooda/Sources/Scenes/NoteList/NoteListReactor.swift, Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
- 노트리스트 서버 수정에 맞게 모델 수정
- cursor 사용하여 cursor가 nil이 올때까지 페이지네이션 이뤄지도록 로직 구성
=> [UI] 노트리스트 화면에서 페이지네이션 로직을 구현했어요

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Core/Coordinator/Scene.swift, Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteStockCellReactor.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- 변동률 입력 화면에서 isEditable 프로퍼티를 추가하고, 생성자에 파라미터로 추가했어요.
- ConfigureUI 메소드에서는 isEidtable 값에 따라 추가/수정 버튼의 타이틀을 변경해줘요.
- Scene에서 변동률 입력 케이스에 isEditable을 전달할 수 있도록 연관값을 추가했어요.
- AppFactory에서 변동률 입력케이스에 isEditable에 따라 modalPresentationStyle을 변경해줘요.
- 노트 등록 ViewController에서 노트 수정과 삭제 이벤트를 전달할 수 있는 Relay를 선언했어요.
- 노트 등록 화면 Reactor에서 변동률 수정 화면을 호출 할 수 있는 로직을 추가하고, completionRelay를 바인딩했어요.
- 변동률 입력화면에서 전달받은 NoteStockItem으로 해당 IndexPath의 SectionItem을 변경해줘요.
- 노트 StockReactor에서 현재 State를 변경할 수 있는 Action과 Mutation을 정의했어요.
- 노트 등록 화면 Reactor에서 삭제 기능을 구현했어요.
|**종목 삭제**|
|--------------------|
|<img src="https://user-images.githubusercontent.com/19662529/148947075-6d4741ed-e06e-4970-a163-88252147376f.gif" width=320>|
|**종목 수정**|
|--------------------|
|<img …
=> [Domain] 노트 등록 화면에서 종목 아이템을 수정하거나 삭제할 수 있어요.

Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTextContentCell.swift, Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift, Tooda/Sources/Scenes/NoteDetail/Cells/NoteStickerCell.swift
- 노트 상세페이지와 관련된 셀(NoteStickerCell, NoteDetailTitleCell, NoteDetailTextContentCell)을 추가
- 관련 셀의 UI 레이아웃 구현
=> [UI] 노트 상세페이지와 관련된 셀들의 기본 UI 레이아웃을 구현했어요

Tooda/Sources/Networking/NetwokringProtocol.swift, Tooda/Sources/Scenes/Home/HomeReactor.swift, Tooda/Sources/Scenes/Home/HomeViewController.swift
- 홈화면에서 목데이터가 아닌 서버에서 받은 노트북을 보여줍니다.
- 서버 response 로깅도 하게 변경했어요.
- createdAt이랑 updatedAt이 없어서 ui는 지금 다르게 보여주고 있어요.
=> [Domain] 홈화면에서 서버에서 받은 노트북 리스트를 받습니다.

Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift, Tooda/Sources/Scenes/NoteDetail/Section/NoteDetailSection.swift
- 노트 상세 화면에 tableView를 추가하고 UI를 설정했어요.
- 노트 상세 화면 tableVieew DataSource로 사용될 DetailSection과 DetailSectionItem을 정의했어요.
=> [Domain] 노트 상세 화면에 tableView을 추가하고 DetailSection을 정의했어요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Core/Coordinator/AppCoordinator.swift, Tooda/Sources/Core/Coordinator/Scene.swift, Tooda/Sources/Entities/Note/AddNoteDTO.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteContentCellReactor.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- AddNoteDTO에 노트 수정과 관련된 프로퍼티를 추가했어요. **id, updatedAt, createdAt**
- ModifiableNoteSectionType을 추가했어요. 전달받은 AddNoteDTO로 NoteSection을 그려줘요.
- `NoteContentCellReactor`에 Payload를 추가하고 State에 프로퍼티로 추가했어요. 그리고 Reactor에 Binding 코드를 추가했어요.
- `NoteImageCellReactor` 생성자에 images를 추가했어요.
- 노트 등록 화면의 Dependency에 modifiableNoteSectionFactory 프로퍼티를 추가하고 modifableNote를 파라미터로 추가했어요.
- 노트 등록 Reactor의 makeSection 로직을 변경했어요. Dependency의 sectionFactory의 유무에 따라서 다른 section을 그려줘요.
- Scene에 modify case를 추가했어요.
- AppFactory에서 createNote와 modifyNote case를 정의했어요.
=> [Domain] 전달된 노트 데이터로 노트 입력 화면을 그려줘요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- 노트 입력 화면에서 노트 등록과 수정을 구분하기 위한 EditMode Enum을 정의했어요.
- 노트 입력 화면에서 EditMode 멤버변수를 정의하고 생성자에 코드를 추가했어요.
- AppFactory에서 EditMode를 다르게 넣어줘요.
- 노트 입력 화면에서 rightBarButton을 computedProperty로 변경하고 editMode에 따라 다른 customView를 반환하도록 변경했어요.
- 수정 버튼 탭에 대한 이벤트를 연결했어요.
=> [Domain] 노트 입력 화면에서 수정 버튼을 추가했어요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Core/AppInject.swift, Tooda/Sources/Entities/AppToken.swift, Tooda/Sources/Networking/API/AuthAPI.swift, Tooda/Sources/Networking/AccessTokenPlugin.swift, Tooda/Sources/Scenes/Login/LoginReactor.swift, Tooda/Sources/Scenes/NoteList/NoteListReactor.swift, Tooda/Sources/Utils/SocialLoginService.swift, Tooda/Tooda.entitlements
- 애플 로그인 구현을 위한 SocialLoginService 추가
- 기존 Device ID 로그인을 애플 로그인으로 수정
- transform 함수 활용하여 애플 로그인 스트림 LoginReactor 연결
https://user-images.githubusercontent.com/31857308/150678625-e696573e-0b5b-45ed-8b8e-a55016e274ba.MP4
=> [Core] 기존 Device ID 로그인을 애플 로그인으로 수정했어요

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Core/Coordinator/Scene.swift, Tooda/Sources/Networking/API/NoteAPI.swift, Tooda/Sources/Scenes/NoteDetail/Cells/NoteStickerCell.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift, Tooda/Sources/Scenes/NoteDetail/Section/NoteDetailSection.swift, Tooda/Sources/Scenes/NoteList/NoteListReactor.swift, Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
- 노트 상세 첫 데이터 로딩 action 추가 및 테이블뷰 state binding
- 노트 리스트 화면 셀 선택 시 화면 라우팅 로직 추가
- 노트 상세 id 전달을 위한 Payload 추가
- 노트 상세 data 잘 오는 것 확인
=> [Core] 노트 리스트 화면에 노트 상세 화면을 연결하고 노트 상세 initial data load 로직을 구현했어요

Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTextContentCell.swift, Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift, Tooda/Sources/Scenes/NoteDetail/Cells/NoteStickerCell.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift, Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
- 셀 데이터 연결
- 노트 리스트 네이게이션 버튼 스펙 아웃에 맞춰 정리
- 노트 디테일 화면 3 dots 버튼 추가 (네이게이션바가 겹치는 이슈 수정 필요)
=> [UI] 노트 디테일 화면 header 부분 타이틀, 내용, 스티커를 볼 수 있어요

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift, Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
**셀의 디자인은 등록 화면 것을 그대로 사용하고 있어 일부 차이가 있을 수 있어요, 추후 QA때 조정할 예정입니다. 🙇🏻‍♂️**
- 노트 상세 화면에 LinkPreview Dependency를 추가했어요.
- 노트 상세 화면 tableView에 종목, 링크 Cell을 등록하고 DataSource 코드를 구현했어요.
- 노트 상세 화면 Reator에서 종목과 링크 갯수에 따른 SectionItem을 만들고 각각의 Section에 넣어줘요.
- 노트 상세 화면 tableView의 타입을 let으로 변경하고, 중복된 Delegate 설정 코드를 제거했어요.
=> [Domain] 노트 상세 화면에서 종목과 링크 아이템을 볼 수 있어요.

Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteStockCell.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
- 노트 입력 화면에서 tableView의 제약조건을 변경했어요.
- 노트 Section과 관련된 Cell들의 제약조건을 변경했어요.
- 노트 입력 화면에서 하단 LinkStackView의 BackgroundColor를 변경했어요.
|변경 전|변경 후|
|--------------------|--------------------|
|<img src="https://user-images.githubusercontent.com/19662529/151557223-87506874-099f-441d-ac6d-a150c4920675.PNG" width=320>|<img src="https://user-images.githubusercontent.com/19662529/151557351-310b56e0-abab-4015-8b5a-80d1f5d5ef21.PNG" width=320>|
=> [UI] 노트 입력 화면과 관련 셀의 제약조건을 변경했어요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Core/Coordinator/Scene.swift, Tooda/Sources/Scenes/AddStock/StockRateInputReactor.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift, Tooda/Sources/Scenes/OneLineReviewPopUp/PopUpReactor.swift
- 노트 상세 화면에서 노트 수정 Alert을 탭 하면 노트 수정 화면을 호출 할 수 있어요.
- 노트 상세 화면에서 Reactor State에 Note 멤버변수를 추가했어요.
- 노트 상세 화면에서 노트 수정화면을 호출 할 때 이벤트를 전달받기 위한 updateRelay를 추가했어요.
- 노트 입력 화면의 Dependency를 클래스 타입으로 바꾸고, updateRelay 프로퍼티를 추가했어요.
- Scene에 노트 수정 Case에 updateRelay 연관 프로퍼티를 추가했어요.
- 노트 입력 화면에서 노트 수정 버튼을 누르면 노트 수정 API를 호출하고 이전 화면에 Relay 이벤트를 전달해요.
- 노트 입력 화면에서 이미지 삭제 버튼을 누르면 RequestDTO에서도 해당 이미지 배열을 제거하는 코드를 추가했어요.
=> [Domain] 노트 상세 화면에서 노트를 수정할 수 있어요.

Tooda/Sources/Core/Coordinator/AppCoordinator.swift
- Coordinator에서 pop로직을 수행할 때, currentViewController의 타입에 따라 다른 처리를 하는 메소드를 추가하고 close 메소드에 적용했어요.
|수정 전|수정 후|
|---------------|---------------|
|![ezgif com-gif-maker (15)](https://user-images.githubusercontent.com/19662529/151550396-f1ab95c0-e7a0-40e9-89af-f2ba05dc1adb.gif)|![ezgif com-gif-maker (16)](https://user-images.githubusercontent.com/19662529/151550427-a5913daf-857e-4ba4-86fd-e76d48e70f75.gif)|
=> [Core] Coordinator의 pop로직을 수정했어요.

Tooda/Sources/Core/Coordinator/AppCoordinator.swift
- Coordinator의 Dismiss 로직에서 completion이 2번 발생할 수 있는 문제를 수정했어요.
|수정 전|수정 후|
|---------------------------|---------------------------|
|![ezgif com-gif-maker](https://user-images.githubusercontent.com/19662529/151697992-d288ebd6-9287-4ce3-8127-dcf897bb580c.gif)|![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/19662529/151697996-69fda883-7424-43d9-a546-8bc0a0b09f6f.gif)|
=> [Core] 화면이 dismiss 될 때, completion이 두번 호출될 수 있는 문제를 수정했어요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
- 노트 상세 화면에서 노트 수정화면을 호출 할 때, completionRelay가 누락되어있어 이벤트를 전달받지 못하는 문제를 수정했어요.
- 노트 수정이 완료되면 dismiss로직을 호출하고 completion 클로저에서 이벤트를 전달하도록 수정했어요.
- 노트 상세 Reactor에서 completionRelay에 불필요한 오퍼레이터를 제거했어요.
=> [Domain] 노트 상세 화면에서 노트 수정에 대한 콜백을 받지 못하는 문제를 수정했어요.

Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- Cell 삭제 SwipeConfiguration을 생성해주는 메소드를 추가했어요.
- 링크 Cell도 Swipe가 가능하게 Delegate 메소드를 수정했어요.
- 노트 입력 화면에서 종목 삭제 이벤트를 전달할 Relay의 이름을 NoteItem으로 변경했어요.
- 노트 입력 Reactor에서 종목 삭제 Action을 아이템 삭제와 관련된 이름으로 변경했어요.
- 노트 링크 SectionItem을 제거해 줄 수 있는 Mutation을 추가했어요.
- 노트 아이템 삭제 Mutation에서는 indexPath를 기반으로 종목과 링크 아이템을 requestNote에서 제거해줘요.
|종목 삭제|링크 삭제|
|-----------------------------|-----------------------------|
|![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/19662529/151699318-f23403da-b435-497d-af62-a6d886f458d8.gif)|![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/19662529/151699328-2b9638a0-18ab-459d-9968-d59c96a268ca.gif)|
=> [Domain] 노트 입력 화면에서 링크 아이템을 삭제할 수 있어요. 그외 SwipeCellConfiguration 기능을 개선했어요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Core/GlobalEventBus/NoteEventBus.swift, Tooda/Sources/Entities/Note/Note.swift, Tooda/Sources/Scenes/Home/HomeReactor.swift, Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift, Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
- 이벤트버스 추가하고 홈화면에 대응했어요.
- 다들 한번 로직 확인해주세요.
- 노트 리스트 화면, 검색 화면, 홈화면: create, edit, delete 이벤트 처리
- 노트 작성 화면:  create, edit, delete 이벤트 방출
=> [Core] 노트에 대한 글로벌 이벤트버스를 추가하고 홈화면에 대응을 합니다. 

Tooda/Sources/Common/UIColor+Extension.swift, Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteStockCellReactor.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- gray6 color가 figma 값과 다른 문제를 수정했어요.
- 종목 기록하기 Cell의 Color를 변경하고 titleLabel에 textStyle을 적용했어요.
- 종목 기록하기 Cell Reactor에 State에 활성화 여부를 표현하는 프로퍼티를 추가했어요. 프로퍼티가 추가됨에 따라 SectionFactory의 코드도 수정했어요. IsEnabeld 값은 종목 갯수를 비교하여 초기화 해요.
- 종목 기록하기 Cell Reactor의 axCount를 표현하는 static 프로퍼티를 추가했어요.
- 종목 기록하기 SectionItem을 새로 그려줄 Mutation을 추가하고 메소드를 구현했어요.
- 종목 아이템 Cell의 Add / Delete Mutation 메소드 내부에서 stock 상태에 따라 다른 SectionItem을 그려주도록 로직을 추가했어요.
- 노트 입력 화면에서 DataSource 클로저 내부에 종목 기록하기 Cell Tap 이벤트에 필터링 오퍼레이터를 추가했어요.
=> [Domain] 종목 기록하기 Cell에 아이템 추가 제한 기능을 추가했어요. 그 외 기타 수정

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Core/Coordinator/Scene.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
- 노트 등록/수정 Reactor Dependency에 NoteEventBus에 대한 PublishSubject 프로퍼티를 추가했어요.
- 노트 등록이 완료되면 화면을 내리고 Completion을 수행할 메소드를 추가했어요.
- 노트 등록/수정 Completion 메소드에서 dismiss completion에 Global Event를 방출하는 로직을 추가했어요.
=> [Domain] 노트 등록/수정 화면에 Global Event에 대한 의존성을 추가하고, 등록/수정 이후에 이벤트를 전달해요.

Tooda/Sources/Common/Extensions/UIImage+Extension.swift, Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailImageCell.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift, Tooda/Sources/Scenes/NoteDetail/Section/NoteDetailSection.swift, Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
- UIImage를 특정 width 비율로 계산된 사이즈의 이미지로 변환하는 Extension 메소드를 추가했어요.
- 노트 리스트 Reactor에서 NoteListDTO를 매핑할 때 쓰는 .map 오퍼레이터를 변경했어요.
- 노트 상세 DetailImageCell을 추가했어요.
- 노트 상세 SectionItem에서 Image case의 연관값의 타입을 String에서 Data로 변경했어요.
- 노트 상세 Reactor에서 이미지 Section을 만들어주기위한 Mutation 메소드와 case를 정의했어요.
- 노트 상세 Reactor에서 SectionModel을 만들 때 스트림간의 Scheduler를 변경했어요.
- 노트 상세 ViewController에 UITableViewDelegate를 채택하고, heightForAt 메소드를 구현했어요. 그로인해 tableView의 불필요한 프로퍼티를 제거하게 되었어요.
=> [Domain] 노트 상세 화면에서 이미지 아이템을 볼 수 있어요.

Tooda/Sources/Common/Extensions/UIImage+Extension.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteLinkCellReactor.swift, Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailImageCell.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift, Tooda/Sources/Scenes/NoteDetail/Section/NoteDetailSection.swift, Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
- NoteLinkCell에 버튼을 추가하고, 탭 이벤트를 Reactive 프로퍼티로 구현했어요.
- 노트 상세 Reactor에 링크 아이템 탭에대한 Action과 Mutation을 구현했어요.
- 노트 상세 ViewController에 링크 아이템 탭 이벤트를 바인딩하는 로직을 추가했어요.
=> [Domain] 노트 상세 화면에서 링크 아이템을 탭하면 인앱 브라우저로 이동할 수 있어요.

Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteImageItemCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteStockCellReactor.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/CreateNote/Section/NoteSection.swift
- 링크 버튼을 눌렀을 때, 현재 Section의 아이템 갯수에따라 유저에게 Alert을 노출해줘요.
- 종목 아이템이 추가되었을 때, 현재 Stock Section의 아이템 갯수에 따라 종목 기록하기 SectionItem을 노출해주는 로직을 추가했어요. Mutation case의 연관값도 변경되었어요.
- 링크 아이템이 삭제될 때, 종목 아이템 삭제 Mutation을 같이 방출해서 크래시가 발생하는 문제를 수정했어요.
- 노트 Section에서 종목 기록하기 SectionItem case에서 불필요한 Reactor 연관값을 제거했어요. 연관값이 제거됨에 따라 SectionItem을 사용하는 부분들의 코드 수정이 발생했어요.
- 노트 컨텐츠가 많아졌을 때, 최하단의 이미지 셀까지 스크롤을 할 수가 없어, 이미지 셀 제약조건을 변경해 스크롤이 가능하게끔 변경했어요.
|링크 아이템 추가/삭제시|
|--------------------------------|
|![링크아이템](https://user-images.githubusercontent.com/19662529/152099872-5b958fe6-bb0f-4a3e-93e6-31ea75dfc821.gif)|
|종목 아이템 추가/삭제시|
|--------------------------------|
|![종목아이템](https://user-images.githubusercontent.com/19662529/152099902-3b67e886-3ca1-4ee7-9b5d-dcce47c58f72.gif)|
|이미지 영역 변경 전|이미지 영역 …
=> [Domain] 노트 등록/수정 화면에 짜잘한 예외처리를 구현했어요.

Tooda/Sources/Common/RxAuthorization.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/SupportFiles/Info.plist
- Info.plist에 카메라 권한 안내 문구 추가하여 크래시가 발생한 문제를 수정했어요.
- RxAuthrization에 camera 관련 옵저버블 프로퍼티 추가
- ImagePickerType을 리액터로 전달하기 위한 열거형 자료형을 추가했어요.
- 노트 입력 화면에서 이미지 액션시트를 눌렀을 때, 카메라/앨범 선택에 따른 Action에 따라 권한을 요청하고, 권한이 거부된 경우 설정화면으로 이동해요. 권한이 허용되어 있으면 각 액션에 맞는 이미지 피커 화면을 호출해요.
=> [Domain] 카메라 권한 관련 기능을 추가하고 이미지 추가 액션시트 기능을 변경했어요.

Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift, Tooda/Sources/Scenes/NoteList/NoteListReactor.swift, Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
- search 버튼 연결
- 노트 리스트 셀에 image count를 표시
- 기존 indicator 로딩 시작 시점 및 종료 시점 네트워크 스트림에 따라 수정
https://user-images.githubusercontent.com/31857308/152367964-6f0765d1-a7c2-48fd-9d73-21362fb47e7d.MP4
=> [UI] 노트 리스트에 search 버튼을 연결하고 노트 리스트 셀에 image count를 표시했습니다!

Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteImageItemCell.swift, Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailImageCell.swift
- 링크 Cell에서 placeHolderView에 설정되어있는 borderLine을 제거했어요.
- 노트 등록/수정 화면에서 링크셀에 대한 수정 스와이프 Action을 수정했어요. Action을 수정함에 따라 기존의 swipe configuration 메소드도 변경했어요.
- 노트 등록/수정 화면에서 URL 변환에 성공했을 때만 link아이템을 만들어 주도록 로직을 수정했어요.
- 노트 등록/수정 시 currentState가 아닌 Mutation 메소드에서 파라미터 값을 통해 API를 수행하도록 수정했어요. **(한줄평이 선택한대로 들어가지 않는 이슈 수정)**
- 변동률 입력하기 화면에 진입했을 때 textField 스트림이 발생해 등록 버튼이 비활성화 되던 문제를 수정했어요.
- String Extension에서 urlImage를 만드는 로직이 성능 이슈가 있어 deprecated 어노테이션을 추가했어요.
- 노트 상세 화면에서 이미지 셀 configure 로직에서 불필요한 동시성제어 로직을 제거했어요.
=> [Domain] 노트 입력/수정 화면과 종목 변동률 입력화면의 이슈를 수정했어요.

Tooda/Sources/Core/AppFactory.swift, Tooda/Sources/Networking/API/NoteAPI.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift, Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
- 노트 삭제 Alert용 메소드를 추가했어요.
- 노트 삭제 AlertController에서 삭제 handler 이벤트를 전달하기 위한 relay 프로퍼티를 추가했어요.
- 노트 상세 Reactor에서 노트 삭제를 위한 Action과 Mutation을 구현했어요.
- 노트 상세 Reactor에 Gloabl 이벤트와 관련된 Depdency를 추가했어요.
- 노트 상세 Reactor Dependency의 payload 프로퍼티를 제거하고 Reactor의 멤버변수로 선언했어요.
- 노트 API에서 삭제 case에 대한 path를 수정했어요.
=> [Domain] 노트 상세 화면에서 노트 삭제 기능을 구현했어요.

Podfile, Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
- 이미지 크롭을 위한 써드파티 Dependency를 추가했어요. [참고](https://github.com/guoyingtao/Mantis)
- 노트 등록/수정 화면에서 사진을 찍거나 앨범에서 사진을 선택하면 이미지를 커스텀할 수 있는 CropViewController를 호출하게 변경했어요.
=> [Utils] 노트 등록/수정 화면에서 사진이나 앨범을 선택하면 CropView를 사용할 수 있어요.

Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
- 노트 등록/수정 화면에서 등록/수정 API에 에러가 발생하면 스낵바를 보여줘요.
- 노트 등록/수정 화면에서 등록/수정 > 한줄평 팝업 입력을 할때, 키보드를 내려줘요.
=> [Domain] 노트 등록/수정 화면에서 네트워킹 에러 처리를 위한 스낵바를 추가했어요. 그외 기타 기능 추가

Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/OneLineReviewPopUp/PopUpReactor.swift
- PopUpReactor에서 링크 urlString을 dismiss completion에서 전달하게 수정했어요.
- 노트 등록/수정 Reactor에서 AlertType case에 title 파라미터를 추가했어요.
- 사진, 링크 추가시 전달할 Alert 형식과 문구를 변경했어요.
=> [Domain] 노트 등록/수정 화면에서 기본 Alert에 title과 message를 볼 수 있어요.

Tooda/Sources/Common/Extensions/Date+Extension.swift, Tooda/Sources/Common/Extensions/Moya+Decoder.swift, Tooda/Sources/Common/Extensions/String+Extension.swift
- toodaMap에서 decoder의 dateFormat을 iso8601로 변경했어요.
- DateFormatType에서 불필요한 server프로퍼티를 변경했어요.
=> [Utils] 서버로부터 전달받는 DateFormmat 형식을 변경했어요.

Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift, Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift, Tooda/Sources/Scenes/Login/LoginReactor.swift
- 앱 설치 후 최초로, 로그인을 시도했을 때 Reactor에서 로컬 저장소에 앱 토큰을 저장하기 전 홈 화면으로 이동하여 Meta API에 토큰이 전달되지 않는 문제를 수정했어요.
- 노트 등록/수정 화면에 인디케이터를 추가했어요. - 이미지 등록중, 노트 등록/수정 시에 인디케이터를 돌려요.
- 노트 등록/수정 화면에서 피커에서 선택한 이미지의 해상도를 조절했어요. 모바일 환경에서는 0.3이여도 충분히 잘 나오네요.
=> [Domain] 투다의 로그인 관련 이슈를 수정하고 등록/수정 화면을 개선했어요.

Tooda/Sources/Common/Extensions/UIImageView+Extension.swift, Tooda/Sources/Scenes/Settings/SettingsViewController.swift
- NSCache를 사용하여 in-memory image Cache를 추가
- 설정화면에서 bouncing을 block 처리
- 캐시된 이미지 사용되는 것 디버그로 확인
=> [Core] In-memory image Cache를 추가했어요
