Tooda/Sources/Entities/Diary/Diary.swift
Tooda/Sources/Entities/Diary/DiaryImage.swift
Tooda/Sources/Entities/Diary/DiaryLink.swift
Tooda/Sources/Entities/Diary/DiaryStock.swift
Tooda/Sources/Entities/Stock.swift

> 앱내에서 사용할 엔티티를 추가하였습니다. Count_Per_Month 제외

add Diary Entities

---

Tooda/Resources/Colors.xcassets/Contents.json
Tooda/Resources/Colors.xcassets/backgroundWithAlpha40.colorset/Contents.json
Tooda/Resources/Colors.xcassets/gray1.colorset/Contents.json
Tooda/Resources/Colors.xcassets/gray2.colorset/Contents.json
Tooda/Resources/Colors.xcassets/gray3.colorset/Contents.json
Tooda/Resources/Colors.xcassets/gray4.colorset/Contents.json
Tooda/Resources/Colors.xcassets/mainGreen.colorset/Contents.json
Tooda/Resources/Colors.xcassets/subBlue.colorset/Contents.json
Tooda/Resources/Colors.xcassets/subRed.colorset/Contents.json
Tooda/Resources/Colors.xcassets/white.colorset/Contents.json

add ColorSets

---

Tooda/Sources/Common/UI/TextStyle.swift
Tooda/Sources/Core/SceneDelegate.swift
Tooda/Sources/Scenes/HomeViewController.swift

- TextStyle 추가
- 예시 커밋(4fa7ad9)으로 이제 TextStyle 적용하시면 돼요.

TextStyle 추가

---

Tooda/Sources/Core/Coordinator/AppCoordinator.swift

- AppCoordinator에 current가 할당 안 되는 문제를 수정했어요.

Coordinator AppCoordinator 개선

---

Tooda/Sources/Common/UIColor+Extension.swift

- Colors.xcassets 의 Color를 가져올 수 있는 Extension을 추가했어요.
- UIColor(named: .gray1) 를 사용해서 컬러를 사용하시면 됩니당

AppColor 추가

---

Tooda/Sources/Common/Extensions/UIEdgeInsets+Extension.swift

- UIEdgeInsets+Extension 추가
- UIEdgeInsets의 init을 좀 더 편리하게 하기 위해 만들었어요.

UI-UIEdgeInsets init extension 추가

---

Tooda/Sources/Common/Extensions/NSAttributedString+Extension.swift
Tooda/Sources/Common/UI/TextStyle.swift

- "+" 연산 추가
- underline 메소드 추가
- 좀 더 편리한 기능들을 추가했어요.

UI-Sting관련 기능 추가

---

Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteLinkCell.swift
Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift
Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteLinkCellReactor.swift
Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteStockCellReactor.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Tooda/Sources/Scenes/CreateNote/Section/NoteSection.swift

- 노트 작성 화면에서 종목 기록하기에 대한 Cell을 추가하였고, 기존 셀의 이름을 변경하였습니다.
- 약 2달전에 작업한 branch를 쪼갠거 라서 TextStyle, ColorSet이 제대로 안되어있는 상태에요!
- EmptyStockCell을 추가하여 SectionItem, DataSource, SectionFactory 에 구현 코드를 추가했어요.
- EmptyStockCell의 UI코드를 구현했어요.

노트작성 화면 종목 Cell 추가

---

Tooda/Resources/Base.lproj/LaunchScreen.storyboard

- splash UI 수정
| Before | After |
| --- | --- |
| <img width="564" alt="스크린샷 2021-07-24 오후 3 12 28" src="https://user-images.githubusercontent.com/31857308/126859398-ccbade88-9426-4c81-80c5-7dc2448a0905.png"> | <img width="564" alt="스크린샷 2021-07-24 오후 3 08 07" src="https://user-images.githubusercontent.com/31857308/126859403-2f401da4-b0e1-4a50-8f09-ca8b7ab786f3.png">|

[UI] splash 화면 수정

---

Tooda/Sources/Common/Extensions/UIView+Extension.swift

- 레이아웃 작성 편의를 위한 extension 추가 ( addSubviews )
- Codebase UI ( snapkit ) 작성에서 한번에 subview하여 view hierarchy를 보기 편한 extension 함수를 추가했습니다
- Usage
```swift
view.addSubviews(
mainImageView,
loginButton
)
```

[UI] 레이아웃 작성 편의를 위한 extension 추가 ( addSubviews )

---

Tooda/Sources/Common/CommonFunc.swift

- CommonFunc 일부 추가 및 수정
- CommonFunc에 Login 작업을 위해 필요한 value를 추가했습니다!
추가적으로 개인적으로는 이런 식으로 app 전역적 변수를 관리하긴 했는데 
```swift
enum GlobalStore {
static let baseURL: String = "http://15.164.46.210:3000/"
static let deviceUUID: String? = UIDevice.current.identifierForVendor?.uuidString
}
```
메모리 차지하는 부분에서 이득이 있어서 **CommonFunc**을 선호하는 거겠죠? 아무튼 저는 더 좋은 쪽으로 따르도록 하겠습니다!

[Core] CommonFunc 일부 추가 및 수정

---

Tooda/Sources/Common/Extensions/NSAttributedString+Extension.swift

- NSAttributedString Extension replace와 composed 추가
이런식으로 사용하시면 됩니다. 애용해주세요

[UI] NSAttributedString Extension 추가

---

Tooda/Sources/Base/BaseCollectionViewCell.swift
Tooda/Sources/Base/BaseTableViewCell.swift
Tooda/Sources/Common/Extensions/UICollectionViewCell+Extension.swift
Tooda/Sources/Common/Extensions/UITableViewCell+Extension.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift

- BaseCollectionViewCell을 추가하였고, reuse를 위한 identifier Extension Value를 추가했어요.
- BaseCollectionViewCell을 추가했어요.
- TableView, CollectionView Cell의 reuse를 편하게 하기 위한 idenifierExtension Value를 추가했어요.

[UI/Util] TableViewCell, CollectionViewCell Extension, BaseCollectionViewCell 추가

---

Tooda/Sources/Common/Extensions/Array+Extension.swift

- Crash-free 하도록 index 접근하도록 extension 추가
- [safe: {index}] 쓰시면 없는 경우 optional 방출하는 extension 입니다.

[Util] 안전한 array index 접근을 위한 Extension 추가

---

Tooda/Sources/Common/UIColor+Extension.swift

중복 생성 color 제거 (gray5)

---

Tooda/Sources/Scenes/Home/Cells/NotebookCell.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift

- 홈화면의 노트북 CollectionView에 페이징을 구현
- 재사용 문제 해결
- 오타 수정
- 페이징을 억지로 만들었는데 뭔가 맘에 안 드네요 담에 고민 더 해볼게요.
https://user-images.githubusercontent.com/24262765/133983055-8959b879-d46c-4f89-a0ed-54f2dc6d56ff.mov

[UI] 홈화면의 노트북 CollectionView에 페이징을 구현합니다.

---

Tooda/Sources/Common/Extensions/Date+Extension.swift
Tooda/Sources/Entities/Notebook/NotebookMeta.swift
Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift

- 커밋 내역 참고
- ViewModel을 어떻게 분리할지 고민이 되네요
https://user-images.githubusercontent.com/24262765/134800611-ffb12ac4-4f5b-4808-9a31-0455a8fe5f4b.mov
)

[UI] 홈 화면에서 상단 title과 subtitle이 노트북 스크롤에 따라 변경됩니다

---

Tooda/Sources/Networking/API/SotckAPI.swift

- SotckAPI 추가 및 enum case, extension 구현

[Network] StockAPI를 추가했어요.

---

Tooda/Sources/Scenes/Home/DatePicker/JSDatePicker.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift

- JSDatePicker추가
- 날짜 선택에 필요한 커스텀 datePicker 추가
-
https://user-images.githubusercontent.com/24262765/139568998-a6aea9fb-d6c3-434d-8cf7-d60d01d7b693.mov

[UI] 날짜선택에 필요한 커스텀 datePicker를 추가합니다

---

Tooda/Sources/Entities/Notebook/NotebookMeta.swift
Tooda/Sources/Scenes/Home/HomeReactor.swift

- 커밋내역참고
- 현재 날짜가 없을 때만 placeholder 나타내기
-

[UI] 노트북 리스트에서 현재 날짜에 노트가 없으면 placeholder 노트북을 보여줍니다.

---

Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Tooda/Sources/Core/SceneDelegate.swift
Tooda/Sources/Scenes/Login/LoginReactor.swift

- AppCoordinator start 함수 수정 및 root 변경으로 로그인 수정
- start 함수 Scene 활용 및 UINavigationController 감쌀 수 있도록 수정
- 로그인 후 root 변경으로 수정
https://user-images.githubusercontent.com/31857308/139524471-a3e48dd7-d6c3-4ec5-8f77-a63752149b62.mp4

[Core] AppCoordinator start 함수 수정 및 root 변경으로 로그인 수정

---

Tooda/Sources/Common/Extensions/UIImage+Asset.swift
Tooda/Sources/Scenes/AddStock/AddStockViewController.swift

- 종목 기록하기 VC NavigationTitle 추가
- 종목 기록하기 VC RightBarButton 추가
- 종목 기록하기 VC TableView, DataSource 정의

[UI] 종목 기록하기 ViewController의 UI를 구현했어요.

---

Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift

- 이제 원하는 노트북으로 이동해요.
-
https://user-images.githubusercontent.com/24262765/139573997-87467032-c456-4521-bde2-f9253c0ea80e.mov

[UI] datePicker에서 date를 픽하면 원하는 노트북으로 이동합니다.

---

Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift

[UI] NoteListCell UI를 구현했어요

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift
Tooda/Sources/Scenes/Search/SearchReactor.swift
Tooda/Sources/Scenes/Search/SearchViewController.swift

- 새로운 빈 검색화면을 볼 수 있습니다.
https://user-images.githubusercontent.com/24262765/140594086-9f8b1999-a2f0-4071-9102-56786ede6da3.mov

[UI] 새로운 검색화면을 볼 수 있습니다.

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift

- Scene 주식 종목에 대한 Case를 추가했어요.
- Scene 요구사항이 변경됨에 따라 의존성이 있는 AppFactory, AppCoordinator에 switch 로직을 구현했어요.
- 주식 종목 Cell에 주식 종목 Did Tap에 대한 Reactive Extension을 구현했어요.
- 노트 등록 ViewController에서 노트 Tap에 대한 Binding 로직을 구현했어요.

[Domain] 주식 종목 입력하기 화면에 대한 Coordinator를 적용했어요.

---

Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift

-  imageCountLabel을 MarginLabel로 수정하고 레이아웃 구성했어요

[UI] imageCountLabel을 MarginLabel로 수정했어요

---

Tooda/Sources/SupportFiles/Info.plist

- Xconfig 파일의 앱 번들 Id를 가져오도록 다시 코드를 수정했어요.

[Utils] Info.plist 번들 id 참조 값 변경

---

Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
Tooda/Sources/Scenes/AddStock/AddStockViewController.swift

- TextField를 추가하고 바인딩 로직을 구현했어요.
- TextField의 Style을 적용하기 위한 Font와 Color enum을 추가했어요.
- Reactor State에 Section 프로퍼티를 추가했어요.
- TextField Input 이벤트를 처리하기 위한 Action, Mutation을 정의했어요.

[UI] 종목 기록하기 화면에 TextField를 추가하고 이벤트를 일부 구현했어요.

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Scenes/NoteList/NoteListReactor.swift

[UI] 노트리스트 화면을 볼 수 있습니다. 

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Tooda/Sources/Scenes/AddStock/Cells/StockItemCellReactor.swift
Tooda/Sources/Scenes/AddStock/Section/AddStockSectionFactory.swift

> #74 PR과 연결되는 PR이에요.
- 종목검색결과 SectionFactory Type protocol을 정의하고 구현체를 설계했어요.
- 종목검색 Reactor의 Dependency에 SectionFactory에 대한 의존성을 추가했어요.
- 종목검색 API의 결과 response를 가지고 searchTextDidChanged의 기능을 구현했어요.

[Domain] 종목 검색 결과 API Response로 Section을 만들어줘요.

---

Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift

- 홈 화면 네이게이션 버튼에 Settings 화면 라우팅 추가
https://user-images.githubusercontent.com/31857308/140622023-79acd1ff-036c-49d2-8348-285b61989f46.mp4

[UI] 홈 화면 버튼에 Settings 화면을 연결했어요

---

Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Tooda/Sources/Scenes/AddStock/Cells/StockItemCell.swift
Tooda/Sources/Scenes/AddStock/Cells/StockItemCellReactor.swift

- 종목 검색 셀의 UI에 Label 프로퍼티를 추가했어요.
- Reactor의 name을 label에 fetch 하는 메소드를 구현했어요.

[UI] 종목 검색 결과 아이템의 UI를 구현했어요.

---

Tooda/Sources/Common/UI/TextStyle.swift
Tooda/Sources/Common/UIColor+Extension.swift
Tooda/Sources/Scenes/Search/SearchViewController.swift

[UI] 검색화면에 검색바 UI를 구성합니다.

---

Tooda/Sources/Base/BaseViewController.swift

- Base뷰컨 import 문제 수정, import UIKit  추가했어요.

[Bug] Base뷰컨 import 문제 수정

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift
Tooda/Sources/Scenes/Search/SearchViewController.swift

[UI] 검색화면에 빈 최근 검색어 화면을 볼 수 있어요.

---

Tooda/Sources/Entities/Note/Note.swift
Tooda/Sources/Entities/Note/NoteLink.swift
Tooda/Sources/Networking/API/NoteAPI.swift
Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Tooda/Sources/Scenes/NoteList/NoteListViewController.swift

- 노트리스트 api 연결 (pagnation 추후 수정)
- 불필요한 코드 제거 및 일부 cell UI 수정
- NoteListCell UI 부족한 부분 다른 PR에서 추가적인 부분 업데이트 예정
https://user-images.githubusercontent.com/31857308/141675176-743d4537-ce3a-4397-b482-399e15cbeb5d.MP4

[UI] 노트 리스트에서 서버에서 온 노트 리스트를 볼 수 있어요

---

Tooda/Sources/Entities/Note/NoteStock.swift

- 종목 변동률 상태를 표현하는 열거형 자료형에서 View에서 사용할 TitleText Extension 프로퍼티를 추가했어요.
- 같은 이유로 TitleColor Extension 프로퍼티를 추가했어요.

[Util] 종목 변동률 열거형에 Extension 변수를 정의했어요.

---

Tooda/Sources/Common/Extensions/UIApplication+Extension.swift
Tooda/Sources/Common/Extensions/UIImage+Asset.swift
Tooda/Sources/Common/Extensions/UILabel+Extension.swift
Tooda/Sources/Common/UIColor+Extension.swift
Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
Tooda/Sources/Scenes/NoteList/NoteListViewController.swift

- NoteListViewController 네비게이션바 수정
- NoteListCell에 더보기 추가 및 일부 UI 업데이트
- 더보기 부분을 truncated 영역 찾기가 어려워서 [StackOverFlow](https://stackoverflow.com/questions/32309247/add-read-more-to-the-end-of-uilabel) 참조하여 extension으로 추가하였는데 NSTextStorage, NSTextContainer 부분에 대한 이해가 부족해서
좀 더 이해하고 쓰려고 했으나 너무 시간을 걸릴 것 같아서 일단 추가하고 나중에 수정이 필요하면 수정하도록 하겠습니다.
- 셀에 나오는 날짜 형식이 구글링으로 예상해서 여러 형식 넣어서 시도해봤지만 변환하는 부분이 계속 실패해서 형식 파악 후 수정 예정

[UI] NoteListCell에서 '더보기', NoteListViewController에서 더보기, 검색버튼을 볼 수 있어요

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentKeywordCell.swift
Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift
Tooda/Sources/Scenes/Search/SearchViewController.swift
Tooda/Sources/Utils/UserDefaultsService.swift

- 최근 검색어를 로컬에 저장하고 볼 수 있습니다. 
https://user-images.githubusercontent.com/24262765/144057470-4f9e73bf-d833-4482-9624-655eec691c06.mov

[Domain] 최근 검색어를 로컬에 저장하고 볼 수 있습니다. 

---

Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
Tooda/Sources/Scenes/AddStock/AddStockViewController.swift

- TableView 셀 아이템을 탭하면 다음 버튼을 활성화 시켜줘요.
- 탭한 셀 아이템의 텍스트를 TextField에 붙여줘요.

[UI] 종목 검색 결과 리스트 아이템 탭 이벤트를 구현했어요.

---

Tooda/Sources/Entities/Note/NoteStock.swift
Tooda/Sources/Scenes/AddStock/StockRateInputReactor.swift
Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift
Tooda/Sources/Scenes/AddStock/View/RateSelectView.swift

- 변동률의 상태를 나타내는 StockChangeState 열거형 자료형의 case이름을 lowercase로 변경했어요.

[Entity] 종목 변동률 case를 lowercase로 변경했어요.

---

Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentKeywordCell.swift
Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentTitleCell.swift
Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift

- create에도 업데이트 로직 추가
- 모두 지우기, 개별 삭제 기능 추가
https://user-images.githubusercontent.com/24262765/145700044-752eec4f-1b01-40ab-a03e-a4e5ccee6f81.mov

[Domain] 최근 검색어를 삭제할 수 있습니다.

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
Tooda/Sources/Scenes/Search/SearchViewController.swift

- 빈 검색결과 화면 추가
- 검색을 완료하면 빈 검색결과 화면을 보여줍니다.

[UI] 검색화면에서 빈 검색결과 화면을 볼 수 있습니다.

---

Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift
Tooda/Sources/Scenes/Search/SearchViewController.swift

[Domain] 최근 검색어의 짜잘한 비즈니스 로직을 처리합니다.

---

Tooda/Sources/Common/Extensions/UIView+Extension.swift

- generateGradient 메소드를 추가했어요.
- configureShadow 메소드를 추가했어요.

[UI] UIView에 Gradient와 Shadow를 적용할 수 있어요.

---

Tooda/Sources/Common/Extensions/UIView+Extension.swift
Tooda/Sources/Scenes/CreateNote/View/CreateNoteGuideView.swift

1. UIView Extension 메소드의 파라미터를 피그마에서 요구하는 alpha, x,y,b,s 으로 변경했어요.
2. CreateNoteGuideView에서 CALayer Extension 메소드를 1번과 같이 변경했어요.

[Util] UIView에 shadow extension 로직을 개선했어요.

---

Podfile
Project.swift
Tooda/Resources/GoogleService-Info.plist
Tooda/Sources/Core/AppDelegate.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift
Tooda/Sources/Scenes/Login/LoginReactor.swift

- Tooda에 Firebase Analytics와 Firebase Crashlystics 추가

[Core] Tooda에 Firebase Analytics와 Firebase Crashlystics를 설정했어요

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Networking/API/SearchAPI.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
Tooda/Sources/Scenes/Search/SearchViewController.swift

- 검색화면에서 검색 결과를 볼 수 있습니다.
- 서버에 목데이터가 없어서 더미데이터 직접 넣었어요.

[Domain] 검색화면에서 검색 결과를 볼 수 있습니다.

---

Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentSectionModel.swift
Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift

- 인디게이터에 inset이 같이 먹어져서 수정했어요.

[UI] 최근 검색어 화면에서 inset을 조정합니다.

---

Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
Tooda/Sources/Scenes/Search/SearchViewController.swift

- 최근 검색어 갯수는 10개까지 보여줍니다.
- 검색바를 포커스하면 최근 검색 화면을 보여줍니다.
- 최근 검색어를 클릭하면 검색바에도 반영합니다.

[Domain] 검색 화면에서 짜잘한 인터렉션을 추가합니다.

---

Tooda/Sources/Entities/Note/AddNoteDTO.swift
Tooda/Sources/Networking/API/NoteAPI.swift

- 노트 등록을 위한 AddNoteDTO 구조체를 정의하고, asParameter 메소드를 구현했어요.
- NoteAPI 파라미터 타입을 변경하고, task로직을 구현했어요.

[Entity] 노트 등록을 위한 DTO를 추가했어요.

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift

[UI] 빈 노트 상세 화면을 추가합니다.

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift
Tooda/Sources/Scenes/NoteList/NoteListViewController.swift

- 라우팅 로직 추가
https://user-images.githubusercontent.com/24262765/147850170-57dc4ae5-2e75-40ab-a0e4-d66803b132d5.mov

[UI] 홈화면에서 노트리스트 화면을 볼 수 있습니다.

---

Tooda/Sources/SupportFiles/Info.plist

- plist를 수정하여 light 모드를 강제하는 value 추가
- dark 모드에서 색반전 없이 잘 나오는 것 기기로 확인

[Core] plist를 수정하여 light 모드를 강제하도록 했어요

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Entities/Settings/PlainSettingsInfo.swift
Tooda/Sources/Entities/Settings/SettingsSectionModel.swift
Tooda/Sources/Scenes/Settings/SettingsReactor.swift
Tooda/Sources/Scenes/Settings/SettingsViewController.swift

- 인앱 브라우저를 추가 (SFSafariViewController 활용)
- 설정 기본 리스트 제거 및 수정
- modal로 연결하였으나 animation은 push로 동작하는 이슈가 있고 debug해도 present하고 있어서 
원인 파악 후 추후 bug fix PR로 수정예정
https://user-images.githubusercontent.com/31857308/149199649-a59a4346-2ee3-4e64-80f9-a07d148e4a4d.mp4

[UI] 설정 기본 리스트를 수정하고 인앱 브라우저를 추가하여 연결했어요

---

Tooda/Sources/Entities/Note/Note.swift
Tooda/Sources/Entities/Note/NoteListModel.swift
Tooda/Sources/Scenes/NoteList/NoteListViewController.swift

- RxTableViewSectionedAnimatedDataSource로 수정하고 AnimatableSectionModelType 만족하도록 수정

[UI] 노트 리스트 화면에서 RxTableViewSectionedAnimatedDataSource을 사용하도록 수정했어요

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Networking/API/NoteAPI.swift
Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Tooda/Sources/Scenes/NoteList/NoteListViewController.swift

- payload 홈에서 받아서 reactor에서 호출하는 API 및 NoteList 화면 Navigation title 수정
- mock data (2022), modal 방식 수정 및 dismiss action 추가
https://user-images.githubusercontent.com/31857308/148964610-802dd95d-4100-4484-b496-9f193318aaa1.mp4

[UI] 홈 화면에서 보내주는 Payload에 맞춰 라우팅 수정했어요

---

Tooda/Sources/Networking/API/NoteAPI.swift

- NoteAPI에 detail case를 추가했어요.

[Network] 노트 상세 API를 추가했어요.

---

Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTextContentCell.swift
Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift
Tooda/Sources/Scenes/NoteDetail/Cells/NoteStickerCell.swift
Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Tooda/Sources/Scenes/NoteList/NoteListViewController.swift

- 기존 cell required init 빠진 부분 추가
- 노트 리스트 화면 노트 추가 버튼에 노트 생성화면을 연결
https://user-images.githubusercontent.com/31857308/150667277-5bf84338-a3d6-4cf1-907f-a16fcd15b931.mp4

[UI] 노트 리스트 화면에 노트 생성화면을 연결했어요

---

Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift

[Domain] 홈화면에서 과거나 미래 노트북을 볼 수 있습니다.

---

Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift

[Bug] 홈화면에서 initialState를 크래시 안 나게 수정합니다.

---

Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Entities/Note/NoteRequestDTO.swift
Tooda/Sources/Networking/API/NoteAPI.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift

- AddNoteDTO의 이름을 NoteRequestDTO로 변경했어요.
- 노트 등록 Reactor에서 사용하는 addNoteDTO 멤버변수의 이름을 변경했어요.

[Domain] 노트 등록 DTO의 이름을 변경했어요.

---

Tooda/Sources/Entities/Note/NoteRequestDTO.swift
Tooda/Sources/Networking/API/NoteAPI.swift

- NoteReqeustDTO의 asParameter 메소드에 id 파라미터를 추가했어요.
- NoteAPI에 update case를 추가했어요.

[Domain] 노트 수정 API를 추가했어요.

---

Tooda/Sources/Common/Extensions/UIAlertController+Extension.swift
Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Entities/Settings/SettingsSectionModel.swift
Tooda/Sources/Networking/API/AuthAPI.swift
Tooda/Sources/Scenes/Settings/SettingsReactor.swift
Tooda/Sources/Scenes/Settings/SettingsViewController.swift

- 탈퇴하기 api 추가
- 탈퇴하기, 로그아웃 관련 SettingsReactor, SettingsViewController 수정
- UIAlertController rx extension 추가
- 탈퇴하기, 로그아웃 관련 모델 수정
https://user-images.githubusercontent.com/31857308/150824088-627753d9-9809-4840-abfe-d4817474fe8e.MP4

[UI] 설정화면에 로그아웃과 탈퇴하기를 추가했어요

---

Tooda/Sources/Common/Extensions/Moya+Decoder.swift
Tooda/Sources/DTO/Note/SearchNoteResponse.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift
Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift

- 검색 결과를 서버에서 받아올 수 있습니다.
- 매핑문제도 해결했어요. (toodaMap)

[Domain] 검색 결과를 서버에서 받아올 수 있습니다.

---

Tooda/Sources/Common/Extensions/Date+Extension.swift

- 날짜의 요일과 시간, 분을 표시해줄 수 있는 case 을 추가했어요.

[Utils] DateComponetType Case를 추가했어요.

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/SceneDelegate.swift
Tooda/Sources/Entities/Note/NoteRequestDTO.swift
Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift
Tooda/Sources/Scenes/NoteDetail/Section/NoteDetailSection.swift
Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Tooda/Sources/Scenes/NoteList/NoteListViewController.swift

- 노트 리스트에 노트 삭제, 수정, 추가 이벤트 버스를 연결
- 노트 리스트에 로딩 인디케이터 추가
- 자동 로그인 block 코드 제거

[Core] 노트 리스트에 이벤트 버스를 연결하고 로딩 인디케이터를 추가했어요

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift

- 검색결과 화면에 글로벌 이벤트 처리를 할 수 있습니다.

[Domain] 검색결과 화면에 글로벌 이벤트 처리를 할 수 있습니다.

---

Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Tooda/Sources/Scenes/Search/SearchViewController.swift

[Bug] 텍스트필드의 attributedString관련한 문제를 수정합니다.

---

Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift

- 홈화면에서 빈 이번달 노트북을 클릭하면 노트 생성화면으로 이동합니다.
- 지금 서버문제로 버그가 있어서 불가

[UI] 홈화면에서 빈 이번달 노트북을 클릭하면 노트 생성화면으로 이동합니다.

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift

- 검색 결과 화면에서 노트상세 화면으로 이동할 수 있습니다.
https://user-images.githubusercontent.com/24262765/152287718-200416a6-405a-4faa-abe5-d3a94fd58a1e.MP4

[UI] 검색 결과 화면에서 노트상세 화면으로 이동할 수 있습니다.

---

Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift

- 노트 등록/수정 Reactor에서 숫자 값들을 Const로 변경했어요.

[Domain] 노트 등록/수정 화면에서 사용하는 숫자를 상수로 변경했어요.

---

Tooda/Sources/Entities/Note/NoteStock.swift
Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift
Tooda/Sources/Scenes/AddStock/View/RateButton.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
Tooda/Sources/Scenes/Home/Cells/NotebookCell.swift
Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift

- 자체 QA후, 짜잘한 UI들을 수정합니다. 커밋으로 확인해주세요.

[UI] 자체 QA후, 짜잘한 UI들을 수정합니다.

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/GlobalEventBus/SnackBarEventBus.swift
Tooda/Sources/Entities/Settings/SettingsSectionModel.swift
Tooda/Sources/Scenes/Login/LoginReactor.swift
Tooda/Sources/Scenes/Login/LoginViewController.swift
Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Tooda/Sources/Scenes/Settings/Cells/SettingsInfoCell.swift
Tooda/Sources/Scenes/Settings/SettingsReactor.swift
Tooda/Sources/Scenes/Settings/SettingsViewController.swift

- 로그아웃, 탈퇴 스낵바와 네트워크 에러 스낵바를 적용
- 로그인 문구 기획대로 일부 수정
https://user-images.githubusercontent.com/31857308/152378409-2bdfa3a8-0cb6-4c3f-b431-97e2dbc164e7.MP4

[UI] 로그아웃, 탈퇴 스낵바와 네트워크 에러 스낵바를 적용했어요!

---

Tooda/Sources/Scenes/NoteList/NoteListViewController.swift

- 노트리스트 네비게이션바 불투명하게 수정
https://user-images.githubusercontent.com/31857308/152549210-2632c5a3-773d-40a3-b1d1-484862f7f96f.MP4

[UI] 네이게이션바가 투명하게 되는 이슈 수정했어요

---

Tooda/Sources/Common/Extensions/UIImageView+Extension.swift
Tooda/Sources/Common/Extensions/UILabel+Extension.swift
Tooda/Sources/Entities/Note/NoteImage.swift
Tooda/Sources/Scenes/CreateNote/Cells/NoteImageItemCell.swift
Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift

- 이미지 width, height 맞춰 셀에서 이미지 레이아웃 업데이트
- 이미지 비동기 load 함수 추가

[UI] dynamic height에 맞춰 이미지 레이아웃을 업데이트 했어요

---

Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTextContentCell.swift
Tooda/Sources/SupportFiles/Info.plist

- 링크 url 생성시 ATS 관련 이슈가 발생하여 info.plist 에 프로퍼티를 추가
- 종목 기록하기 > 텍스트 필드 > placeHolder 추가
- 노트 상세 > 내용 셀 n 줄처리 가능하게 수정
- 노트 등록화면 > 테이블 뷰 > 키보드 레이아웃 제약 조건 추가

[Domain] 각종 QA 이슈를 수정했어요.

---

Tooda/Sources/Core/AppFactory.swift
Tooda/Sources/Core/Coordinator/Scene.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/NoteList/NoteListReactor.swift

- 노트 등록 Scene에서 routeToDetailRelay를 추가했어요.
- 홈 화면 Reactor에 routeToDetailRelay를 추가하고 상세 화면으로 이동하기 위한 Mutation을 구현했어요.
- 리스트 화면 Reactor에 routeToDetailRelay를 추가하고 상세 화면으로 이동하기 위한 Mutation을 구현했어요.

[Domain] 노트 등록이 완료되면 호출한 화면에서 상세 화면으로 이동해요.

---

Tooda/Sources/Scenes/Home/DatePicker/JSDatePicker.swift
Tooda/Sources/Scenes/Home/HomeReactor.swift

- 플레이스홀더 노트북은 무조건 "기록해보세요"로
- toodaMap 적용
- datePick할 때, 생길 수 있는 문제들 수정
- 데이트피커 미래 제거

[Bug] 홈화면 짜잘한 버그들을 수정했어요.

---

Tooda/Sources/Scenes/Home/HomeReactor.swift

- 홈화면에서 defaultIndex를 처리할 수 있습니다.

[UI] 홈화면에서 defaultIndex를 처리할 수 있습니다.

---

Tooda/Sources/Scenes/Home/HomeReactor.swift

[Domain] 홈화면에서 노트관련 글로벌 state 이벤트를 받으면 리로드합니다.

---

Tooda/Sources/Core/GlobalEventBus/SnackBarEventBus.swift
Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Tooda/Sources/Scenes/Home/HomeReactor.swift
Tooda/Sources/Scenes/Home/HomeViewController.swift
Tooda/Sources/Scenes/Login/LoginReactor.swift
Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
Tooda/Sources/Scenes/Settings/SettingsReactor.swift
Tooda/Sources/Utils/SnackBarManager.swift

[Domain] 나머지 에러 핸들링을 추가합니다.

---

Tooda/Sources/Common/Extensions/Date+Extension.swift
Tooda/Sources/Entities/Sticker.swift
Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift
Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Tooda/Sources/Scenes/Settings/SettingsReactor.swift

- 노트 리스트 추가, 삭제 제대로 반영 안되는 이슈를 수정했어요
- 설정에 만든사람들 추가하고 링크를 업데이트 했어요

[UI] QA 수정사항 및 추가사항을 반영했어요

---

Tooda/Sources/Scenes/Login/LoginViewController.swift

- 레이아웃을 조정해서 작은 기기에서 UI 깨지는 이슈를 수정했어요
- iPhone SE2 (수정 이후)

[UI] 기기 대응을 위해 레이아웃을 수정했어요
